import Link from 'next/link';
import Image from 'next/image';
import { ArrowRight, ArrowUpRight, Check, MessageCircle, ShieldCheck, Wallet } from 'lucide-react';
import { getAllCategoriesPublic,getTopCitiesPublic } from '@/lib/queries/home-public';
import { getRecentProjectsForHome } from '@/lib/queries/recent-projects';
import { getFeaturedHomePros } from '@/lib/queries/featured-home-pros';
import { getFichesFraiches } from '@/lib/queries/fraicheur';
import { DEPT_PAR_CATEGORIE } from '@/lib/data/home-links';
import JsonLd from '@/components/seo/JsonLd';
import { getWebSiteSchema,getOrganizationSchema,getFaqSchema } from '@/lib/utils/schema';
import { BASE_URL } from '@/lib/constants';
import MisesAJourSection from '@/components/home/MisesAJourSection';
import HomeFinder from './HomeFinder';
import HomeGallery from './HomeGallery';
import s from './public-glass.module.css';
const faqs=[{question:'Comment déposer un projet ?',answer:'Décrivez votre besoin, indiquez le métier et la commune, puis vos coordonnées. Votre demande est proposée aux professionnels concernés. Ceux qui sont intéressés peuvent vous contacter pour en discuter.'},{question:'Est-ce gratuit pour les particuliers ?',answer:'La consultation de l’annuaire et le dépôt de projet sont gratuits pour les particuliers. Vous choisissez librement la suite des échanges, sans engagement.'},{question:'Puis-je choisir directement un professionnel ?',answer:'Oui. L’annuaire permet de consulter les fiches et leurs coordonnées disponibles. Un dépôt de projet permet de présenter votre besoin à plusieurs professionnels concernés ; il ne constitue pas une réservation auprès d’un professionnel précis.'},{question:'Que signifie une fiche réclamée ?',answer:'Le professionnel a obtenu l’accès à sa fiche pour la gérer. Cela ne constitue pas une certification de ses prestations. Prenez le temps de vérifier les informations et documents adaptés à votre projet.'},{question:'Mes coordonnées sont-elles publiques ?',answer:'Vos coordonnées de dépôt ne sont pas affichées dans les exemples publics de projets. Elles permettent les échanges avec les professionnels concernés selon le fonctionnement de la plateforme.'}];
export default async function HomeGlass(){
 const [categories,cities,recentProjects,pros,fresh]=await Promise.all([getAllCategoriesPublic(),getTopCitiesPublic(30),getRecentProjectsForHome(12).catch(()=>[]),getFeaturedHomePros().catch(()=>[]),getFichesFraiches(7,24).catch(()=>[])]);
 const seenProjects = new Set<string>();
 const projects = recentProjects.filter(p => { const key = `${p.categoryName}:${p.cityName}:${p.createdAt.slice(0,10)}`; if(seenProjects.has(key)) return false; seenProjects.add(key); return true; }).slice(0,6);
 const groups=[['btp','Travaux & rénovation'],['domicile','Maison & quotidien'],['personne','Aide à la personne']];
 return <main data-glass className={s.home} id="main"><JsonLd data={getWebSiteSchema(BASE_URL)}/><JsonLd data={getOrganizationSchema(BASE_URL)}/><JsonLd data={getFaqSchema(faqs)}/><div className={s.wrap}>
 <section className={s.hero}><div><p className={s.eyebrow}>LES SAVOIR-FAIRE SE RENCONTRENT ICI.</p><h1>Votre projet.<br/>Le bon pro.<br/><span>Tout simplement.</span></h1><p className={s.deck}>Travaux, maison, coups de main :<br/>cherchez un professionnel ou décrivez votre projet.</p><div className={s.actions}><Link prefetch={false} href="/deposer-projet" data-project-cta="home-hero" className={s.primary}>Décrire mon projet<ArrowRight size={19}/></Link><Link prefetch={false} href="/recherche" className={s.textLink}>Chercher un pro<ArrowUpRight size={18}/></Link></div><p className={s.assurance}><Check size={17}/>Gratuit pour les particuliers. Sans engagement.</p></div><HomeGallery pros={pros}/></section>
 <HomeFinder categories={categories.map(c=>({slug:c.slug,name:c.name,vertical:c.vertical}))}/><div className={s.benefits}><span><Wallet size={18}/>Mise en relation gratuite</span><span><MessageCircle size={18}/>Échanges directs</span><span><ShieldCheck size={18}/>Coordonnées non publiques</span></div>
 <section className={s.section} id="projects"><div className={s.sectionHead}><div><p className={s.eyebrow}>DERRIÈRE CHAQUE PROJET, UNE ENVIE.</p><h2>Ils ont fait le premier pas.<br/><span>Et vous ?</span></h2></div><p>Des besoins du quotidien, des idées qui prennent forme. Votre projet a aussi sa place ici.</p></div>{projects.length>0?<div className={s.cards}>{projects.map(p=><article className={s.project} key={p.id}><p className={s.eyebrow}>{p.categoryName}</p><h3>{p.categoryName}<br/>à {p.cityName}.</h3><p>{p.teaser||'Une demande déposée sur Workwave. Son contenu et les coordonnées du particulier restent privés.'}</p><p className={s.cardMeta}>Déposé le {new Date(p.createdAt).toLocaleDateString('fr-FR',{timeZone:'Europe/Paris'})} · {p.cityName}{p.postalCode?` (${p.postalCode})`:''} · coordonnées privées</p><Link prefetch={false} data-project-cta="home-project-example" className={s.cardAction} href={`/deposer-projet?categorie=${encodeURIComponent(p.categorySlug)}`}>J’ai aussi un projet<ArrowRight size={17}/></Link></article>)}</div>:<div className={s.empty}><p>Une idée en tête ? Décrivez votre besoin pour commencer.</p><Link prefetch={false} href="/deposer-projet" data-project-cta="home-project-empty" className={s.primary}>Décrire mon projet<ArrowRight size={18}/></Link></div>}<p className={s.note}>Exemples anonymisés de demandes enregistrées. Leur affichage ne garantit ni disponibilité ni réponse.</p></section>
 <section className={s.section} id="professionals"><div className={s.sectionHead}><div><p className={s.eyebrow}>DES VISAGES, DES MÉTIERS, DU SAVOIR-FAIRE.</p><h2>Prenez le temps de découvrir.<br/><span>Puis le temps d’échanger.</span></h2></div><Link prefetch={false} href="/recherche" className={s.textLink}>Explorer l’annuaire<ArrowRight size={18}/></Link></div>{pros.length>0?<div className={s.cards}>{pros.map(pro=><article key={pro.slug}><Link prefetch={false} href={`/artisan/${pro.slug}`} className={s.proPhoto}><Image src={pro.photo} alt={`Photo de la galerie de ${pro.name}`} fill sizes="(max-width:760px) 100vw, 32vw"/><span>Découvrir sa fiche<ArrowUpRight size={18}/></span></Link><div className={s.proInfo}><h3><Link prefetch={false} href={`/artisan/${pro.slug}`}>{pro.name}</Link></h3><p>{pro.trade} · {pro.city}</p></div></article>)}</div>:<p>Parcourez l’annuaire pour découvrir les professionnels selon votre besoin et votre commune.</p>}<p className={s.note}>Photos publiées dans les galeries professionnelles. Prestations et zone d’intervention à confirmer avec chaque professionnel.</p></section>
 <section className={s.section}><p className={s.eyebrow}>À CHAQUE BESOIN, SON POINT DE DÉPART.</p><h2>Qu’avez-vous en tête ?</h2><div className={s.needs}>{groups.map(([vertical,title])=><div className={s.needGroup} key={vertical}><h3>{title}</h3><ul>{categories.filter(c=>c.vertical===vertical).map(c=><li key={c.slug}><Link prefetch={false} href={DEPT_PAR_CATEGORIE[c.slug]?`/${c.slug}/${DEPT_PAR_CATEGORIE[c.slug]}`:`/${c.slug}`}>{c.name}<ArrowUpRight size={15}/></Link></li>)}</ul></div>)}</div></section>
 <section className={`${s.section} ${s.how}`} id="how"><div><p className={s.eyebrow}>ON VOUS ACCOMPAGNE.</p><h2>Un premier pas.<br/><span>Et ça commence.</span></h2><p>Un besoin à expliquer.<br/>Des échanges pour décider.</p><Link prefetch={false} className={s.primary} href="/deposer-projet" data-project-cta="home-how">Décrire mon projet<ArrowRight size={18}/></Link></div><ol>{[['Racontez-nous votre besoin.','Quelques mots sur votre projet et sa localisation. On vous guide pour les précisions.'],['Échangez avec les professionnels.','La demande est proposée aux pros concernés. Ceux qui sont intéressés peuvent vous contacter pour en discuter.'],['Choisissez à votre rythme.','Discutez, comparez les propositions et décidez librement.']].map(([title,text],i)=><li key={title}><span>{i+1}</span><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol></section>
 <section className={`${s.section} ${s.faq}`}><div><p className={s.eyebrow}>LES RÉPONSES, EN TOUTE SIMPLICITÉ.</p><h2>Avant de vous lancer.<br/><span>On vous répond.</span></h2></div><div>{faqs.map(f=><details key={f.question}><summary>{f.question}<span>+</span></summary><p>{f.answer}</p></details>)}</div></section>
 <nav className={s.localLinks} aria-label="Trouver un professionnel dans votre ville"><h2>Les professionnels près de chez vous</h2>{cities.map(c=><Link prefetch={false} key={c.id} href={`/plombier/${c.slug}`}>{c.name}</Link>)}</nav>
 <MisesAJourSection pages={fresh}/></div></main>;
}
