import puppeteer from "puppeteer-core";
import os from "os"; import path from "path";
const CHROME="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome";
const b=await puppeteer.launch({executablePath:CHROME,headless:"new",args:["--no-sandbox","--hide-scrollbars"]});
const p=await b.newPage(); const errs=[];
p.on("pageerror",e=>errs.push(e.message)); p.on("console",m=>m.type()==="error"&&errs.push(m.text()));
await p.setViewport({width:1100,height:1500,deviceScaleFactor:2});
await p.goto("http://localhost:3000/barometre-penurie-artisans",{waitUntil:"domcontentloaded",timeout:60000});
await new Promise(r=>setTimeout(r,2500));
await p.screenshot({path:path.join(os.homedir(),"Desktop","penurie-full.png"),fullPage:true});
const y=await p.evaluate(()=>{const h=[...document.querySelectorAll("h2")].find(e=>e.textContent.includes("métier par métier"));return h?h.getBoundingClientRect().top+scrollY:0;});
await p.evaluate(yy=>scrollTo(0,yy-20),y); await new Promise(r=>setTimeout(r,500));
await p.screenshot({path:path.join(os.homedir(),"Desktop","penurie-carte.png"),clip:{x:0,y:0,width:1100,height:1200}});
console.log("erreurs:",errs.length?errs.slice(0,3):"AUCUNE");
const info=await p.evaluate(()=>({paths:document.querySelectorAll("svg path").length,opts:document.querySelectorAll("select option").length}));
console.log("paths SVG:",info.paths,"| options métier:",info.opts);
await b.close();
